version: 2
jobs:
  run_smoke_test:
    working_directory: ~/teacher-vacancy-service
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
        RAILS_ENV: test
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec --tag smoke_test spec/smoke_test/

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_smoke_test:
          filters:
            branches:
              only:
                - develop
  # scheduled-smoke-tests:
  #   triggers:
  #     - schedule:
  #         cron: "5,10,15,20,25,30,35,40,45,50,55,0 * * * *"
  #         filters:
  #           branches:
  #             only: master
  #   jobs:
  #     - run_smoke_test
